// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDsXckDnrWszUUlKtLjRibLUK_uLUsCo',
    appId: '1:456757511456:web:03f84aaa79d26d49f34345',
    messagingSenderId: '456757511456',
    projectId: 'ecommerce-app-a7866',
    authDomain: 'ecommerce-app-a7866.firebaseapp.com',
    storageBucket: 'ecommerce-app-a7866.firebasestorage.app',
    measurementId: 'G-PKKWNEGSCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCL0jSNaJJt4yJEdwtpVUuh10f5XmMuOU',
    appId: '1:456757511456:android:0d34f5f88b36a3d0f34345',
    messagingSenderId: '456757511456',
    projectId: 'ecommerce-app-a7866',
    storageBucket: 'ecommerce-app-a7866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEBv8UOFVstkgplGfyXmPqKYFQkPe2yGo',
    appId: '1:456757511456:ios:9d0cd9e3e0697170f34345',
    messagingSenderId: '456757511456',
    projectId: 'ecommerce-app-a7866',
    storageBucket: 'ecommerce-app-a7866.firebasestorage.app',
    iosBundleId: 'com.example.fruitsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEBv8UOFVstkgplGfyXmPqKYFQkPe2yGo',
    appId: '1:456757511456:ios:9d0cd9e3e0697170f34345',
    messagingSenderId: '456757511456',
    projectId: 'ecommerce-app-a7866',
    storageBucket: 'ecommerce-app-a7866.firebasestorage.app',
    iosBundleId: 'com.example.fruitsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzxNboQTTBM9-LcGITO1D4JhRkQubRAec',
    appId: '1:456757511456:web:24daf671972bb619f34345',
    messagingSenderId: '456757511456',
    projectId: 'ecommerce-app-a7866',
    authDomain: 'ecommerce-app-a7866.firebaseapp.com',
    storageBucket: 'ecommerce-app-a7866.firebasestorage.app',
    measurementId: 'G-NRVK4ZEFY9',
  );
}
